### ISSUE TITLE
Sub: Adjust styling on hero banner/nav menu

### ISSUE THREAD

**Issue by EliNygard** [NoroffFEU/musikkforandrerliv.no#1074]
**Description:**
The hero banner is shorter than the design. It could have something to do with the header taking up so much space, it is not the correct design either. Another team is responsible, we will design the banner according to its design regardless. The buttons in the nav menu are covering the title element on mobile view, make adjustments to match the design.

Merge the PR to the `feat-our-work-page-epic7` branch.

Design file: https://www.figma.com/design/p3IKXs5ICTeFKQQ5hZ4ZAG/Design-File---MMF?node-id=0-1&p=f&t=WkatSoVmYzAORMa8-0

Styling on banner and nav menu in mobile view now:

![Image](https://github.com/user-attachments/assets/15ac7c40-7c2d-4452-9e60-f3cb67315ff4)

The correct design for banner and nav menu: 

![Image](https://github.com/user-attachments/assets/dc50839d-b75c-4923-9f5c-ddcf5146dea9)

Space between title and nav menu on tablet/desktop view now: 

![Image](https://github.com/user-attachments/assets/faab7cb1-aab4-4ed8-8da6-fdcf680d9548)

The correct design for space between title and nav menu:

![Image](https://github.com/user-attachments/assets/b0736f6a-92e5-425f-8f12-e0905eb32af2)

**Tasks:** 
- [ ] Adjust the banner size
- [ ] Place nav menu below title on mobile view
- [ ] Add more space between title and nav menu on tablet and desktop view

🪄 Ask another developer or in the team chat if you need assistance on code
🪄 Questions regarding the issue, comment and tag the SM

**Comment by TheRegzi** [comment]
I tried to fix it, does it look better? For me, the icons were not covering the title, so I think @EliNygard need to check it. :) Here is the PR: https://github.com/NoroffFEU/musikkforandrerliv.no/pull/1083

**Comment by EliNygard** [comment]
I'll check now!

**Comment by EliNygard** [comment]
I opened your PR and in the browser it looks like this. Is it not the same at your end? 😅

![Image](https://github.com/user-attachments/assets/02b8dcd9-bacc-488d-b673-59099d22de83)

**Comment by EliNygard** [comment]
HOW STRANGE! 😄 I use Chrome. It's 100% correct! I'll let @gydalo look at this and merge if it is okay. She will then run some tests.

**Comment by gydalo** [comment]
This is really weird. For me it also looks like Eli's version, but I will look at it more tomorrow morning or later today!

**Comment by TheRegzi** [comment]
Super weird 😥
I’m not sure if this will help, but did you try npm install -> npm run build -> npm run dev?
If it doesn’t work, maybe another developer from our team should fix it ?

**Comment by EliNygard** [comment]
I did that, still the same 😅 Yes, I'll ask for help from the team 🪄

**Comment by Whisperpiano** [comment]
Going to check on this :)
